url: brighthive.github.io
baseurl: 

# Site settings
title: BrightHive
email: info@brighthive.io
description: "BrightHive is a technology company building and supporting the open source infrastructure necessary to transform the way social services providers, government agencies, and funders share data securely and ethically to directly improve the wellbeing of the individuals they serve."
address: "20 West Kinzie, Suite 1700, Chicago, IL 60654"
twitter: brighthiveio
github: brighthive
linkedin: brighthiveio
docs: "https://docs.brighthive.io/"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll


# Build settings
markdown: kramdown
permalink: pretty